hw11 completed
mayerkv/otus_go_homework pull request #12
Opened 2022-06-26 09:42 UTC by mayerkv

## Домашнее задание №11 «Клиент TELNET»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 2 баллов
- [ ] Понятность и чистота кода - до 4 баллов

#### Зачёт от 7 баллов

2022-06-26 09:46 UTC, mayerkv commented on hw11_telnet_client/main.go
> +		if err := client.Close(); err != nil {
линтер агрится на то что якобы интерфейс `TelnetClient` не имеет метода `Close`, хотя в него встроен инотерфейс `io.Closer`

2022-06-29 15:33 UTC, agneum requested changes
Спасибо за выполненное задание. 
Хорошая работа, однако возвращаю решение на доработку, поскольку пайплайн не пройден.
Так же будет здорово, если получится добавить новые юнит-тесты
Итого: 4 балла из 10

2022-06-29 15:33 UTC, agneum commented on hw11_telnet_client/main.go
> +		if err := client.Close(); err != nil {
Я бы предложил обновить линтер до версии (v1.45.2), поддерживающей Go 1.18 
https://github.com/mayerkv/otus_go_homework/blob/master/.github/workflows/tests.yml#L25

2022-06-29 15:33 UTC, agneum commented on hw11_telnet_client/main.go
> +	wg.Wait()
Кажется, что в решении дублируется функциональность контекста и waitGroup

2022-06-29 15:33 UTC, agneum commented on hw11_telnet_client/telnet.go
> +	return c.conn.Close()
Желательно проверить, что `c.conn` не `nil`

2022-06-29 17:57 UTC, mayerkv commented on hw11_telnet_client/main.go
> +		if err := client.Close(); err != nil {
Спасибо! Поднял версию.

2022-06-29 17:57 UTC, mayerkv commented on hw11_telnet_client/main.go
> +	wg.Wait()
исправил

2022-06-29 17:57 UTC, mayerkv commented on hw11_telnet_client/telnet.go
> +	return c.conn.Close()
исправил

2022-06-30 09:32 UTC, agneum approved these changes
Спасибо за правки. 10/10

2022-06-30 14:40 UTC, merged